name: queen-attack
version: 2.2.0.7

dependencies:
  - base

library:
  exposed-modules: Queens
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - lens  

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - queen-attack
      - hspec
